FROM node:18-alpine

RUN npm install -g serve

ARG USER=default

RUN adduser -D -h /home/$USER -u 1001 $USER

USER $USER

WORKDIR /home/$USER

COPY --chown=$USER:$USER . .

RUN npm ci && npm run build:frontend  && rm -rf node_modules

WORKDIR /home/$USER/frontend/

CMD [ "serve", "-s", "build" ]